config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mains
  resources :publishers
  resources :sakusyas
  resources :titles
  get 'top/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Defines the root path route ("/")
  root "top#index"
end

app/models/sakusya.rb
class Sakusya < ApplicationRecord
    has_many :mains
    belongs_to :user, optional: true
end

app/controllers/sakusyas_controller.rb
class SakusyasController < ApplicationController
  before_action :set_sakusya, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sakusyas or /sakusyas.json
  def index
    @sakusyas = Sakusya.where(user_id: current_user.id)
  end

  # GET /sakusyas/1 or /sakusyas/1.json
  def show
    @main = Sakusya.find_by(id: params[:id])
  end

  # GET /sakusyas/new
  def new
    @sakusya = Sakusya.new
  end

  # GET /sakusyas/1/edit
  def edit
  end

  # POST /sakusyas or /sakusyas.json
  def create
    @sakusya = Sakusya.new(sakusya_params)
    @sakusya.user_id = current_user.id

    respond_to do |format|
      if @sakusya.save
        format.html { redirect_to sakusya_url(@sakusya), notice: "新しい作者を登録しました！" }
        format.json { render :show, status: :created, location: @sakusya }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sakusya.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sakusyas/1 or /sakusyas/1.json
  def update
    respond_to do |format|
      if @sakusya.update(sakusya_params)
        format.html { redirect_to sakusya_url(@sakusya), notice: "作者情報をアップデートしました！" }
        format.json { render :show, status: :ok, location: @sakusya }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sakusya.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sakusyas/1 or /sakusyas/1.json
  def destroy
    @sakusya.destroy

    respond_to do |format|
      format.html { redirect_to sakusyas_url, notice: "作者情報を削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sakusya
      @sakusya = Sakusya.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sakusya_params
      params.require(:sakusya).permit(:name).merge(user_id: current_user.id)
    end
end

app/helpers/sakusyas_helper.rb
module SakusyasHelper
end

app/views/sakusyas/_form.html.erb
<%= form_with(model: sakusya) do |form| %>
  <% if sakusya.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sakusya.errors.count, "error") %> prohibited this sakusya from being saved:</h2>

      <ul>
        <% sakusya.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit "決定" %>
  </div>
<% end %>

app/views/sakusyas/_sakusya.html.erb
<div id="<%= dom_id sakusya %>">
  <p>
    <strong>Name:</strong>
    <%= sakusya.name %>
  </p>

</div>

app/views/sakusyas/edit.html.erb
<h1>作者名の編集</h1>

<%= render "form", sakusya: @sakusya %>

<br>

<div>
  <%= link_to "戻る", @sakusya %> |
  <%= link_to "作者リストに戻る", sakusyas_path %>
</div>

app/views/sakusyas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>作者の登録</h1>

<div id="sakusyas">
  <% @sakusyas.each do |sakusya| %>
    <p>
      <div class="con"><%= render sakusya %><%= link_to "詳細を見る", sakusya %></div>
    </p>
  <% end %>
</div>

<p class="newlink"><%= link_to "新規登録", new_sakusya_path %></p>

app/views/sakusyas/new.html.erb
<h1>New sakusya</h1>

<%= render "form", sakusya: @sakusya %>

<br>

<div>
  <%= link_to "Back to sakusyas", sakusyas_path %>
</div>

app/views/sakusyas/show.html.erb
<h2>詳細</h2>

<div class="con">
  <%= render @sakusya %>
</div>

<div>
  <%= link_to "この作者名を編集する", edit_sakusya_path(@sakusya) %> |
  <%= link_to "作者リストに戻る", sakusyas_path %>

  <%= button_to "この作者名を削除", @sakusya, method: :delete %>
</div>