config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mains
  resources :publishers
  resources :sakusyas
  resources :titles
  get 'top/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Defines the root path route ("/")
  root "top#index"
end

app/models/title.rb
class Title < ApplicationRecord
    has_many :mains
    belongs_to :user, optional: true
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /titles or /titles.json
  def index
    @titles = Title.where(user_id: current_user.id)
  end

  # GET /titles/1 or /titles/1.json
  def show
    @title = Title.find_by(id: params[:id])
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles or /titles.json
  def create
    @title = Title.new(title_params)
    @title.user_id = current_user.id

    respond_to do |format|
      if @title.save
        format.html { redirect_to title_url(@title), notice: "新しいタイトルを登録しました！" }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1 or /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to title_url(@title), notice: "タイトル情報をアップデートしました！" }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1 or /titles/1.json
  def destroy
    @title.destroy

    respond_to do |format|
      format.html { redirect_to titles_url, notice: "タイトル情報を削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def title_params
      params.require(:title).permit(:name).merge(user_id: current_user.id)
    end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_with(model: title) do |form| %>
  <% if title.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
        <% title.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit "決定" %>
  </div>
<% end %>

app/views/titles/_title.html.erb
<div id="<%= dom_id title %>">
  <p>
    <strong>Title: </strong><%= title.name %>
  </p>

</div>

app/views/titles/edit.html.erb
<h1>タイトルの編集</h1>

<%= render "form", title: @title %>

<br>

<div>
  <%= link_to "戻る", @title %> |
  <%= link_to "タイトルリストに戻る", titles_path %>
</div>

app/views/titles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>タイトルの登録</h1>

<div id="titles">
  <% @titles.each do |title| %>
    <div class="con"><%= render title %><%= link_to "詳細を見る", title %></div>
  <% end %>
</div>

<p class="newlink"><%= link_to "新規登録", new_title_path %></p>

app/views/titles/new.html.erb
<h1>新しいタイトルを登録しよう</h1>

<%= render "form", title: @title %>

<br>

<div>
  <%= link_to "タイトル一覧に戻る", titles_path %>
</div>

app/views/titles/show.html.erb
<h2>詳細</h2>

<div class="con">
  <%= render @title %>
</div>

<div>
  <%= link_to "このタイトルを編集する", edit_title_path(@title) %> |
  <%= link_to "タイトルリストに戻る", titles_path %>

  <%= button_to "このタイトルを削除", @title, method: :delete %>
</div>