config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mains
  resources :publishers
  resources :sakusyas
  resources :titles
  get 'top/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Defines the root path route ("/")
  root "top#index"
end

app/models/main.rb
class Main < ApplicationRecord
    validates :user_id, {presence: true}
    belongs_to :title
    belongs_to :sakusya
    belongs_to :publisher
    belongs_to :user, optional: true
    def user
        return Main.find_by(id: self.id)
    end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /mains or /mains.json
  def index
    if params[:title_key]
      @mains = Main.joins(:title).where(user_id: current_user.id).where('name LIKE ?', "%#{params[:title_key]}%")
    elsif params[:sakusya_key]
      @mains = Main.joins(:sakusya).where(user_id: current_user.id).where('name LIKE ?', "%#{params[:sakusya_key]}%")
    else
      @mains = Main.where(user_id: current_user.id)
    end
  end

  # GET /mains/1 or /mains/1.json
  def show
    @main = Main.find_by(id: params[:id])
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains or /mains.json
  def create
    @main = Main.new(main_params)
    @main.user_id = current_user.id

    respond_to do |format|
      if @main.save
        format.html { redirect_to main_url(@main), notice: "新しい購入情報が登録されました！" }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1 or /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to main_url(@main), notice: "購入情報をアップデートしました！" }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1 or /mains/1.json
  def destroy
    @main.destroy

    respond_to do |format|
      format.html { redirect_to mains_url, notice: "購入情報を削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_params
      params.require(:main).permit(:title_id, :number, :sakusya_id, :date, :publisher_id).merge(user_id: current_user.id)
    end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/_form.html.erb
<%= form_with(model: main) do |form| %>
  <% if main.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
        <% main.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title_id, "タイトル", style: "display: block" %>
    <%= form.select :title_id, Title.where(user_id: current_user.id).map{|o| [o.name, o.id]} %>
  </div>

  <div id="num">
    <%= form.label :number, "巻", style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :sakusya_id, "作者名", style: "display: block" %>
    <%= form.select :sakusya_id, Sakusya.where(user_id: current_user.id).map{|o| [o.name, o.id]} %>
  </div>

  <div>
    <%= form.label :date, "購入日", style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :publisher_id, "出版社名", style: "display: block" %>
    <%= form.select :publisher_id, Publisher.where(user_id: current_user.id).map{|o| [o.name, o.id]} %>
  </div>

  <div>
    <%= form.submit "決定" %>
  </div>
<% end %>

app/views/mains/_main.html.erb
<div id="<%= dom_id main %>">
  <p>
    <strong>タイトル:</strong>
    <% if main.title.present? %>
      <%= @main.title.name %>
    <% else %>
      タイトルが空です
    <% end %>
  </p>

  <p>
    <strong>巻:</strong>
    <%= main.number %>巻
  </p>

  <p>
    <strong>作者:</strong>
    <% if @main.sakusya.present? %>
      <%= @main.sakusya.name %>
    <% else %>
      作者名が空です
    <% end %>
  </p>

  <p>
    <strong>購入日:</strong>
    <%= main.date %>
  </p>

  <p>
    <strong>出版社:</strong>
    <% if @main.publisher.present? %>
      <%= @main.publisher.name %>
    <% else %>
      出版社名が空です
    <% end %>
  </p>

</div>

app/views/mains/edit.html.erb
<h1>Editing main</h1>

<%= render "form", main: @main %>

<br>

<div>
  <%= link_to "戻る", @main %> |
  <%= link_to "マンガリストに戻る", mains_path %>
</div>

app/views/mains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>今持っているマンガはこちら</h1>

<div id="mains">
  <% @mains.each do |main| %>
    <p>
      <% if main.title.present? %>
        <%= main.title.name %>
      <% else %>
        タイトルが空です
      <% end %>
      <% if main.sakusya.present? %>
        <%= main.sakusya.name %>
      <% else %>
        作者名が空です
      <% end %>
      <%= main.number %>巻
      <%= link_to "詳細を見る", main %>
    </p>
  <% end %>
</div>

<div id="title_search">
  <%= form_tag('/mains', method:'get') do %>
    <%= label_tag(:title_key, 'タイトルを検索:') %>
    <%= text_field_tag(:title_key) %>
    <%= submit_tag('Search') %>
    <%= link_to '全表示', mains_path %>
  <% end %>
</div>

<div id="sakusya_search">
  <%= form_tag('/mains', method:'get') do %>
    <%= label_tag(:sakusya_key, '作者を検索:') %>
    <%= text_field_tag(:sakusya_key) %>
    <%= submit_tag('Search') %>
    <%= link_to '全表示', mains_path %>
  <% end %>
</div>

<p class="newlink"><%= link_to "新規登録", new_main_path %></p>

app/views/mains/new.html.erb
<h1>New main</h1>

<%= render "form", main: @main %>

<br>

<div>
  <%= link_to "Back to mains", mains_path %>
</div>

app/views/mains/show.html.erb
<h2>詳細</h2>

<div class="con">
<%= render @main %>
</div>

<div>
  <%= link_to "このマンガを編集", edit_main_path(@main) %> |
  <%= link_to "マンガリストに戻る", mains_path %>

  <%= button_to "この情報を削除", @main, method: :delete %>
</div>